#ansible-playbook -i inventory/dc_inventory.yml dc_config.yml -kK

- name: Create ADDC
  hosts: windows
  vars_prompt:
    - name: safe_mode_password
      prompt: "Enter Safe Mode Password Here"
      private: true

    - name: adminpassword
      prompt: Please enter your admin password
      private: true

  tasks:
  # Set Hostname
  - name: set hostname to dc-1
    ansible.windows.win_hostname:
      name: '{{ hostname }}'
    register: hostnamereboot
  # Reboot after hostname is set to finalize the customization
  - name: Reboot
    ansible.windows.win_reboot:
    when: hostnamereboot.reboot_required

  # Validate that Windows has rebooted and can be managed again 
  - name: Validate before moving on
    ansible.windows.win_reboot:
       test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'


  # Reset admin password
  - name: reset administrator password
    ansible.windows.win_user:
      name: Administrator
      password: "{{ adminpassword }}"
      state: present

  # # Join a target to the domain
  # - name: Create new domain in a new forest on the target host
  #   ansible.windows.win_domain:
  #     dns_domain_name: blue.local
  #     safe_mode_password: '{{safe_mode_password}}'
  
  # Create new Windows Domain
  - name: Create new Windows domain in a new forest
    ansible.windows.win_domain:
      create_dns_delegation: false
      dns_domain_name: blue.local
      safe_mode_password: '{{safe_mode_password}}'
    register: domain_install

  - name: Reboot
    ansible.windows.win_reboot:
    when: domain_install.reboot_required

  
# Add user to domain admins
  - name: Add user to Admin Groups
    community.windows.win_domain_user:
      name: "{{ ansible_user }}"
      state: present
      groups_action: add
      groups:
        - Domain Admins
        - Enterprise Admins

# # Promote the server to domain controller
#   - name: Promote Server
#     ansible.windows.win_domain_controller:
#       dns_domain_name: blue.local
#       domain_admin_user: '{{ansible_user}}'
#       domain_admin_password: '{{adminpassword}}'
#       safe_mode_password: '{{safe_mode_password}}'
#       state: domain_controller
#     register: dc_promotion
  
#   #Reboot after domain promotion
#   - name: Reboot after promotion
#     ansible.windows.win_reboot:
#     when: dc_promotion.reboot_required
  

  # Create new OU
  - name: Create OUs
    community.windows.win_domain_ou:
      name: "{{ item.name }}"
      path: "{{ item.path }}"
    loop:
      - name: "blue"
        path: "DC=blue,DC=local"
      - name: "Accounts"
        path: "OU=blue,DC=blue,DC=local"
      - name: "Groups"
        path: "OU=Accounts,OU=blue,DC=blue,DC=local"
      - name: "Computer"
        path: "OU=blue,DC=blue,DC=local"
      - name: "Workstations"
        path: "OU=Computer,OU=blue,DC=blue,DC=local"
      - name: "Servers"
        path: "OU=Computer,OU=blue,DC=blue,DC=local"
