- hosts: graylog
  remote_user: "{{ansible_user}}"
  become: True
  vars:
    #Elasticsearch vars
    es_major_version: "7.x"
    es_version: "7.10.2"
    es_enable_xpack: False
    es_instance_name: "graylog"
    es_heap_size: "1g"
    es_config:
      node.name: "graylog"
      cluster.name: "graylog"
      http.port: 9200
      transport.tcp.port: 9300
      network.host: "127.0.0.1"
      discovery.seed_hosts: "localhost:9300"
      cluster.initial_master_nodes: "graylog"
    oss_version: True
    es_action_auto_create_index: False

    #Graylog vars
    graylog_version: 4.2
    graylog_install_java: True
    graylog_password_secret: "54tgzdbb1l2G487ze7BrvAJu68NyuFxsCA1O0zJjF6TG8JT1S9gWhCl0gEy6i1UZxQYF74ImYbiinVZIf35bQ4FoNA0fEuAu" # Insert your own here. Generate with: pwgen -s 96 1
    graylog_root_password_sha2: "e6260cfaf8fc4ee052016c9021970392a7ed32cff856a8ae58cb4fae17ce6a8c" # Insert your own root_password_sha2 here.
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"

  roles:
    - role: "graylog2.graylog"
      tags:
        - "graylog"